# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Set up JDK 21 on ${{ matrix.os }}
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven on ${{ matrix.os }}
      run: mvn --batch-mode clean package --file pom.xml

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Javagotchi-${{ matrix.os }}
        path: target/*.jar
